version: "3.3"
services:
  postgres: 
    container_name: vehicles_pg
    build:
      context: build/postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password123
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    networks:
      - vehicles_net
  backend:
    container_name: vehicles_backend
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8008:8008"
    volumes:
      - "./solution:/solution"
    networks:
      - vehicles_net
volumes:
  pg_data:
networks:
  vehicles_net:
    driver: bridge
    ipam:
      driver: default

